version: '3.8'

services:
  tunes-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tunes-website
    ports:
      - "0.0.0.0:8088:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: tunes-network
