version: '3.8'

services:
  tunes-web:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
    container_name: tunes-website
    ports:
      - "8088:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
