version: '3.8'

services:
  tunes-web:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
    container_name: tunes-website
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tunes.rule=Host(`tunes-app.com`)"
      - "traefik.http.services.tunes.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-net"

networks:
  proxy-net:
    external: true
