name: Cleanup Docker Images

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean Old Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clean up old images
        run: |
          # Keep last 10 images, delete older ones
          echo "Cleaning up old Docker images..."

          # This would require additional tooling or API calls to Docker Hub
          # For now, we'll just log the cleanup intention
          echo "Cleanup process would remove images older than 30 days"
          echo "Manual cleanup may be required via Docker Hub web interface"
